---
abstract: 'generate C::A::Fast compatible XS accessors'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Accessor-Fast-GXS
no_index:
  directory:
    - example
    - inc
requires:
  perl: 5.8.0
version: 0.01
